# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.graphicsView_5 = PlotWidget(self.tab)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.verticalLayout_2.addWidget(self.graphicsView_5)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.graphicsView_6 = PlotWidget(self.tab)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.verticalLayout.addWidget(self.graphicsView_6)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox_3)
        self.graphicsView_9 = PlotWidget(self.tab)
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.verticalLayout_10.addWidget(self.graphicsView_9)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_4)
        self.graphicsView_10 = PlotWidget(self.tab)
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.verticalLayout_9.addWidget(self.graphicsView_10)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.splitter_7 = QtWidgets.QSplitter(self.tab)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.verticalLayout_12.addWidget(self.splitter_7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_11.setFont(font)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_9)
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_10)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.graphicsView_8 = PlotWidget(self.tab_2)
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.verticalLayout_6.addWidget(self.graphicsView_8)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_7)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_8)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.graphicsView_7 = PlotWidget(self.tab_2)
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.verticalLayout_3.addWidget(self.graphicsView_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.splitter_12 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.splitter_16 = QtWidgets.QSplitter(self.splitter_12)
        self.splitter_16.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_16.setObjectName("splitter_16")
        self.horizontalLayout.addWidget(self.splitter_12)
        self.splitter_17 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_17.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_17.setObjectName("splitter_17")
        self.splitter_18 = QtWidgets.QSplitter(self.splitter_17)
        self.splitter_18.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_18.setObjectName("splitter_18")
        self.horizontalLayout.addWidget(self.splitter_17)
        self.splitter_10 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.splitter_11 = QtWidgets.QSplitter(self.splitter_10)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.horizontalLayout.addWidget(self.splitter_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Image 1"))
        self.pushButton_2.setText(_translate("MainWindow", "Image 2"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Real"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Real"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_8.setText(_translate("MainWindow", "Mixer output to:"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "output 1"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "output 2"))
        self.label_6.setText(_translate("MainWindow", "component 1"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Image 1"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Image 2"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "Real"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.label_7.setText(_translate("MainWindow", "Output 1"))
        self.label_5.setText(_translate("MainWindow", "component 2"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Image 1"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Image 2"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "Imaginary"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "Real"))
        self.label_4.setText(_translate("MainWindow", "Output 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
